services:
  api:
    container_name: ts-express-app-dev
    build:
      target: development-run-stage
    ports:
      - 3000:3000
    environment:
      APP_PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules