services:
  api-unit-tests:
    container_name: ts-express-app-unit-tests
    build:
      context: .
      target: unit-tests-run-stage
    environment:
      APP_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: test-user
      DATABASE_PASSWORD: test-user
      DATABASE_DB: test-ts-app
    depends_on:
      database-migrations:
        condition: service_completed_successfully

  api-e2e-tests:
    container_name: ts-express-app-e2e-tests
    build:
      context: .
      target: e2e-tests-run-stage
    environment:
      APP_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: test-user
      DATABASE_PASSWORD: test-user
      DATABASE_DB: test-ts-app
    depends_on:
      database-migrations:
        condition: service_completed_successfully

  api-e2e-tests-serve:
    container_name: ts-express-app-e2e-tests-serve
    build:
      context: .
      target: e2e-tests-run-and-serve-stage
    environment:
      APP_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: test-user
      DATABASE_PASSWORD: test-user
      DATABASE_DB: test-ts-app
    ports:
      - 8080:8080
    depends_on:
      database-migrations:
        condition: service_completed_successfully

  database-migrations:
    container_name: ts-express-app-migrations
    build:
      context: .
      target: apply-migrations-stage
    environment:
      APP_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: test-user
      DATABASE_PASSWORD: test-user
      DATABASE_DB: test-ts-app
    depends_on:
      - database

  database:
    container_name: ts-express-app-database-tests
    environment:
      POSTGRES_DB: test-ts-app
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-user
    ports:
      - 5432:5432